name = "PointCloudFilters"
uuid = "ce1cfaff-6c62-4fc1-9e13-ab1d2535aa4b"
authors = ["Maarten Pronk", "Deltares"]
version = "0.1.0"

[compat]
julia = "1.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
